version: '3.8'

services:
  postgres:
    image: docker.m.daocloud.io/library/postgres:15-alpine
    container_name: keydo-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: keydo
      POSTGRES_PASSWORD: keydo123
      POSTGRES_DB: keydo_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keydo-network

networks:
  keydo-network:
    driver: bridge

volumes:
  postgres_data:

